import { Injectable } from '@angular/core';
import { Mhs } from './mhs';
import { HttpClient } from '@angular/common/http';
import { MhsFormComponent } from './mhs-form/mhs-form.component';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  baseUrl = 'https://crudcrud.com/api/222ad7ed38784c1c943ba1a04d00e228' ; // berbeda untuk setiap mahasiswa - iya beda ko.

  constructor(private http: HttpClient) {}

  getMhs() {
    return this.http.get(`${this.baseUrl}/mhs`);
  }

  getMhsId(id: number) {
    return this.http.get('${this.baseUrl}/mhs/${id}');
  }

  postMhs(mhs: Mhs) {
    delete mhs._id; // we delete the id because it'll generated by server
    return this.http.post(`${this.baseUrl}/mhs`, mhs);
  }

  updateMhs(mhs: Mhs) {
    const id = mhs._id; // we copy the original id
    delete mhs._id; // we delete the original id so the server doesn't reply with error message
    return this.http.put(`${this.baseUrl}/mhs/${id}`, mhs);
  }

  deleteMhs(mhs: Mhs) {
    const id = mhs._id; // we copy the original id
    return this.http.delete('${this.baseUrl}/mhs/${id}');
  }
}
